Add account settings
NikitaHasl/findrace pull request #19
Opened 2021-09-19 20:22 UTC by julialunati

2021-09-19 21:14 UTC, VoidPhantom requested changes
* Изменение роли лучше убрать. Это нетривиальная задача: если участник изменяется на организатора, то что происходит с его записями? А если организатор меняется на участника, то что происходит с созданными им забегами? Если мы решим в будущем добавлять такую возможность, то это надо будет обдумать. И уж точно не позволять пользователям просто так сделаться администраторами!
* Логику изменения пароля надо убрать не только с фронтенда, но и с бэкенда.

2021-09-19 21:14 UTC, VoidPhantom commented on app/Http/Controllers/UserController.php
> +            return redirect()->route('index')->with('success', 'Аккаунт успешноу дален!');
```suggestion
            return redirect()->route('index')->with('success', 'Аккаунт успешно удален!');
```

2021-09-19 21:14 UTC, VoidPhantom commented on app/Http/Controllers/UserController.php
> +    }
Эти действия не нужны, их лучше убрать (отсюда и из маршрутов)

2021-09-19 21:21 UTC, julialunati commented on app/Http/Controllers/UserController.php
> +            return redirect()->route('index')->with('success', 'Аккаунт успешноу дален!');
done

2021-09-19 21:21 UTC, julialunati commented on app/Http/Controllers/UserController.php
> +    }
ok

2021-09-19 21:24 UTC, VoidPhantom requested changes

2021-09-19 21:24 UTC, VoidPhantom commented on routes/web.php
> +    Route::resource('user', UserController::class)->shallow();
```suggestion
    Route::resource('user', UserController::class)->shallow()->except(['create', 'store', 'show']);
```

2021-09-19 21:25 UTC, NikitaHasl commented on routes/web.php
> +    ->name('user.delete');
UserController - ресурсный, там уже есть роут и действие на удаление, лучше не дублировать.

2021-09-19 21:25 UTC, julialunati commented on routes/web.php
> +    Route::resource('user', UserController::class)->shallow();
done

2021-09-19 21:27 UTC, julialunati commented on routes/web.php
> +    ->name('user.delete');
эт да, но когда делала через destroy то он почему-то видел как show и не удалял :( поэтому и пришла к этому решению

2021-09-19 21:27 UTC, VoidPhantom approved these changes

2021-09-19 21:38 UTC, NikitaHasl commented on routes/web.php
> +    ->name('user.delete');
через route('user.destroy')? там надо посылать через ajax, на курсе по laravel препод говорил, что просто так не отправишь на destroy.

2021-09-19 21:39 UTC, VoidPhantom commented on routes/web.php
> +    ->name('user.delete');
Или делать @method('DELETE')

2021-09-19 21:41 UTC, VoidPhantom requested changes
Действие удаления пользователя не должно использовать метод GET!

2021-09-19 21:44 UTC, julialunati commented on routes/web.php
> +    ->name('user.delete');
ну я честно по-разному пробовала, но только так получилось, чтоб нормально работало. я не профи в этом дела, поэтому если кто знает как правильнее сделать буду благодарна за помощь :)

2021-09-19 21:47 UTC, VoidPhantom commented on routes/web.php
> +    ->name('user.delete');
Нужно, чтобе удаление делалось не ссылкой, а через форму. В форме нужно прописать `method="post"` и Blade-директиву `@method('DELETE')`, чтобы Laravel знал, что это на самом деле DELETE.

Если использовать GET для запросов, изменяющих данные, то может возникнуть куча проблем из-за того, что браузеры делают неверные предположения. Например, бразузер может сделать запрос ещё до того, как пользователь нажал на ссылку, чтобы ответ уже был готов к тому моменту, когда пользователь нажмёт.

2021-09-19 21:58 UTC, julialunati commented on routes/web.php
> +    ->name('user.delete');
через форму сделала, но через destroy все равно пока что не получается, может с утра озарит но пока что только так

2021-09-19 21:59 UTC, VoidPhantom commented on resources/views/user/settings.blade.php
> +                </form>
```suggestion
                <form action="{{ route('user.delete', ['id' => $user->id ]) }}" method="post" rel="{{ $user->id }}">
                    @csrf
                    @method('DELETE')
                    <input class="form-control" type="submit" value="Удалить профиль">
                </form>
```

2021-09-19 22:01 UTC, julialunati commented on resources/views/user/settings.blade.php
> +                </form>
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The DELETE method is not supported for this route. Supported methods: GET, HEAD.
http://localhost/account/user/delete/19

2021-09-19 22:01 UTC, julialunati commented on resources/views/user/settings.blade.php
> +                </form>
тогда такая ошибка

2021-09-19 22:06 UTC, VoidPhantom commented on resources/views/user/settings.blade.php
> +                </form>
А ты убрала лишний маршрут из routes/web.php?

2021-09-19 22:09 UTC, julialunati commented on resources/views/user/settings.blade.php
> +                </form>
почему лишний? если я его удалю то 
Symfony\Component\Routing\Exception\RouteNotFoundException
Route [user.delete] not defined. (View: /var/www/html/resources/views/user/settings.blade.php) и соответственно не знает куда идти чтоб удалять

2021-09-19 22:11 UTC, VoidPhantom commented on resources/views/user/settings.blade.php
> +                </form>
Маршрут уже есть в ресурс-контроллере и называется `account.user.destroy`. То есть нужно написать: `<form action="{{ route('account.user.destroy', ['user' => $user ]) }}"`

И ещё в контроллере действие переименовать из `delete` в `destroy`

2021-09-19 22:19 UTC, julialunati commented on resources/views/user/settings.blade.php
> +                </form>
да так тоже делала и почему-то тогда page expired

2021-09-19 22:26 UTC, julialunati commented on resources/views/user/settings.blade.php
> +                </form>
всееееее!!! получилось! спасибо большое!!!!!

2021-09-19 22:33 UTC, VoidPhantom approved these changes
А ограничения в базе данных исправлены на ON DELETE CASCADE?

Впрочем, мне сейчас уже как-то всё равно, я иду спать ☺

2021-09-19 22:40 UTC, julialunati commented
не, сиды и миграции я не трогала специально, но могу подправить

2021-09-19 22:42 UTC, julialunati commented
теперь работает удаление пользователя даже если он записан на забег

2021-09-20 11:08 UTC, NikitaHasl approved these changes

2021-09-20 11:15 UTC, merged