Add user search and chat
NikitaHasl/findrace pull request #23
Opened 2021-09-22 18:59 UTC by davidbraginsky

1. User Search
- separate page for user search
- two individual inputs for first name and last name
- search works if user knows both full name or only part (e.g. 'Emmet Brown' or 'mme')
- search results show list of matching users with link to user's profile page
- profile page displays more info + button to start chat

2. Chat
- added migrations, controllers and models chat and messages
- messages table stores individual messages with author_id
- chat table stores messages with recipient_id
- after user types in message browser refreshes with new data
- added basic logic and styling to differentiate between own messages and received ones

2021-09-22 21:11 UTC, julialunati commented
как по мне все ок, только хотелось бы добавить какой-нибудь ответ о том что "Такой пользователь не найден" когда пользователя нет в бд (а то сейчас просто серый экран)

2021-09-22 21:13 UTC, julialunati commented on resources/views/chat/chat.blade.php
> +@section('title', 'Создать забег')
@section('title', ' Сообщения')

2021-09-22 21:15 UTC, julialunati commented on resources/views/profile/profile.blade.php
> +@section('title', 'Создать забег')
@section('title', 'Профили')

2021-09-22 21:15 UTC, julialunati commented on resources/views/userSearch/results.blade.php
> +@section('title', 'Создать забег')
@section('title', 'Поиск пользователя')

2021-09-22 21:16 UTC, julialunati commented on resources/views/userSearch/search.blade.php
> +@section('title', 'Создать забег')
@section('title', 'Поиск пользователя')

2021-09-22 21:16 UTC, julialunati approved these changes

2021-09-23 11:31 UTC, VoidPhantom requested changes
Я не понимаю структуру новых таблиц. Что такое `chat` и что такое `message`?

У нас теперь уже есть целых три контроллера, связанных с пользователями: `UserController`, `AccountController` и `ProfileController`. Не стоит ли их как-то упростить?

И ещё в `ChatController` не хватает валидации данных.

2021-09-23 11:31 UTC, VoidPhantom commented on database/migrations/2021_09_22_165431_create_messages_table.php
> +            $table->string('content');
Нужно сделать нормальные типы в базе данных, включая связи

2021-09-23 11:31 UTC, VoidPhantom commented on database/migrations/2021_09_22_165534_create_chat_table.php
> +            $table->string('message_id');
Тоже нужно сделать нормальные типы

2021-09-23 11:31 UTC, VoidPhantom commented on resources/lang/en/validation.php
> +    | of "email". This simply helps us make our chat more expressive.
Не понял, что это вообще за изменения в этом файле?

2021-09-23 11:31 UTC, VoidPhantom commented on routes/web.php
> +    ->name('chat.store');
Маршруты для чата должны быть ограничены только для зарегистрированных пользователей. Либо здесь, либо в конструкторе контроллера —  скорее лучше там

2021-09-23 11:31 UTC, VoidPhantom commented on app/Http/Controllers/RaceController.php
> +        // title, description, start, finish - поля, по которым нужно искать
```suggestion
            // title, description, start, finish - поля, по которым нужно искать
```

2021-09-23 11:31 UTC, VoidPhantom commented on app/Http/Controllers/ProfileController.php
> +        $profile = User::where('id', $id)->get();
```suggestion
        $profile = User::find($id);
```
Тогда возвращается одна модель и не нужно делать `$profile[0]` в представлении.

А ещё лучше — сделать model binding, чтобы Laravel сам достал модель или вывел относительно нормальную страницу 404.

2021-09-23 11:31 UTC, VoidPhantom commented on app/Http/Controllers/ChatController.php
> +        $recipient = User::where('id', $recipient_id)->get();
```suggestion
        $recipient = User::find($recipient_id);
```

2021-09-23 11:42 UTC, davidbraginsky commented on database/migrations/2021_09_22_165431_create_messages_table.php
> +            $table->string('content');
Message  -  таблица в которой хранятся все созданные сообщения. Не важно кто кому что написал. Есть текст сообщения и есть автор сообщения. 

Chat - связующая таблица, в которой есть как само сообщение через message_id так и то кому адресовано сообщение через recipient_id.

Контроллеры можно совместить, согласен, но это уже из серии фиксов, а не добавления функционала. Оптимизировать можно до бесконечности. Если у тебя есть желание и возможность отрефакторить, всегда пожалуйста) Я сегодня уже не успею ничего сделать.

2021-09-23 11:43 UTC, davidbraginsky commented on resources/lang/en/validation.php
> +    | of "email". This simply helps us make our chat more expressive.
Не знаю, я это не трогал)

2021-09-23 11:45 UTC, VoidPhantom commented on database/migrations/2021_09_22_165431_create_messages_table.php
> +            $table->string('content');
Зачем две отдельных таблицы? Одно сообщение может быть адресовано нескольким людям? Если нет, то почему не хранить `recipient_id` в таблице `message`?

2021-09-23 11:49 UTC, VoidPhantom commented on database/migrations/2021_09_22_165431_create_messages_table.php
> +            $table->string('content');
И кстати, Laravel, кажется, ожидает названия таблиц в множественном числе: `messages`. Там автоматический выбор всяких названий завязан на это.

2021-09-23 11:51 UTC, VoidPhantom commented on resources/lang/en/validation.php
> +    | of "email". This simply helps us make our chat more expressive.
Blame с этим не согласен ☺

2021-09-23 12:00 UTC, NikitaHasl commented on app/Http/Controllers/ChatController.php
> +            ->get();
Выражение неправильно построено, потому что будут найдены все записи, в которых получатель пользователь. Получается мешанина, потому что в чатах с другими людьми будут отображаться левые сообщения.

2021-09-23 12:04 UTC, VoidPhantom commented on app/Http/Controllers/ChatController.php
> +            ->get();
Ого! Здорово, что заметил.
Ещё здесь не хватает сортировки по времени создания, чтобы сообщения выводились в разумном порядке.

2021-09-23 12:08 UTC, NikitaHasl commented on database/migrations/2021_09_22_165431_create_messages_table.php
> +        });
Не совсем понимаю, зачем хранить отдельно авторов и получателей. Не понимаю, почему получатель в сущности чата. Довольно таки неудобный способ хранения. Может имеет смысл в сущности чата хранить пользователей, у которых переписка, а уже в сущности сообщения сами тексты сообщений? Просто на курсе по БД мы проектировали БД для условного "Вконтакте" и вот там совсем другая реализация была, как мне показалось более удобная.

2021-09-23 12:11 UTC, NikitaHasl requested changes
.

2021-09-27 13:35 UTC, VoidPhantom commented
Если ты решил совместить новый `ProfileController` вместе со старым `UserController`, то тогда, наверно, `ProfileController` нужно вообще удалить.

Также нужно исправить вышеупомянутые мелочи по поводу комментариев. И вроде всё, больше проблем я не вижу, можно мёрджить.

2021-09-27 13:45 UTC, davidbraginsky commented
Каких комментариев?

2021-09-27 13:50 UTC, VoidPhantom commented
Ну я же выше упомянул про почему-то изменившийся комментарий в файле `resources/lang/en/validation.php` и изменившийся отступ в комметарии в `RaceController.php`. Нужно просто эти изменения откатить.

2021-09-27 14:05 UTC, VoidPhantom approved these changes

2021-09-27 15:33 UTC, NikitaHasl approved these changes

2021-09-27 15:49 UTC, merged