updated race page styling
NikitaHasl/findrace pull request #35
Opened 2021-09-29 00:02 UTC by davidbraginsky

2021-09-29 13:08 UTC, NikitaHasl approved these changes
Всё отлично, есть мелкие замечания.

2021-09-29 13:08 UTC, NikitaHasl commented on resources/views/races/show.blade.php
> +                </div>
т.к. этот функционал не реализован, предлагаю эти кнопки убрать.

2021-09-29 13:08 UTC, NikitaHasl commented on resources/views/races/show.blade.php
> +                <span class="race__time">9:00:00</span>
время есть в бд, я думаю что надо брать оттуда.

2021-09-29 13:08 UTC, NikitaHasl commented on resources/views/races/show.blade.php
> +                    <div class="race__infoContent">{{$race->start}}</div>
зачем в карточке 2 раза прописывать время начала?

2021-09-29 13:08 UTC, NikitaHasl commented on resources/views/races/show.blade.php
> +                <p>Сейчас ты можешь записаться на дистанцию и сразу ее оплатить.</p>
Про оплату мне кажется стоит убрать информацию, т.к. функционала ещё нет.

2021-09-29 13:56 UTC, VoidPhantom requested changes

2021-09-29 13:56 UTC, VoidPhantom commented on resources/views/races/show.blade.php
> +                        <button><a href="{{ route('subscribe', ['id' => $race->id]) }}">Записаться</a></button>
Всё-таки финальную вёрстку следует сделать по-нормальному. Ссылка внутри кнопки — это не только семантически неправильно, но ещё и работает плохо: при наведении на всю кнопку она подсвечивается и меняется курсор, но нажимать можно только на ссылку.

«Добавить результаты» и «Список участников» следует сделать обычными ссылками, а вот «Записаться» должна быть формой, чтобы запись всё-таки можно было потом сделать нормально через POST (#10).

И кстати, про добавление результатов: сейчас, если зайти из-под организатора, страница чужого забега выглядит вот так:
![screenshot](https://user-images.githubusercontent.com/8202373/135280853-2f0c81e4-2820-4fe4-9da2-d6b2dd28a017.png)

Лучше в таком случае вообще убрать такой блок. А если организатор смотрит на свой забег — оставить, но написать там что-нибудь другое.

2021-09-29 13:56 UTC, VoidPhantom commented on resources/views/layout/main.blade.php
> +            <a class="nav__item" href="{{ route('userSearch') }}">Чат</a>
Кажется, чат — какая-то «недоваренная» фича, так что ссылку на него лучше убрать. Тем более что она ведёт не на чат, как написано, а на поиск пользователей.

2021-09-29 14:39 UTC, VoidPhantom commented
Ещё есть комментарий: если у забега картинка, у которой aspect ratio не такое же, как у той картинки, которая сейчас отображается на этой странице, то она отображается на всю ширину страницы, а высота меняется:
![screenshot](https://user-images.githubusercontent.com/8202373/135290345-9f8c1cb8-afed-4a6b-aa3c-96a31f34fb0e.png)

Тут уж вопрос к дизайнерам и фронтендерам, как лучше поступать в такой ситуации: может быть, картинку лучше обрезать или растянуть до фиксированной высоты? Я не настаиваю ни на каком варианте; просто информирую о том, что происходит.

2021-09-29 17:48 UTC, julialunati commented on resources/views/races/show.blade.php
> +                        <button><a href="{{ route('subscribe', ['id' => $race->id]) }}">Записаться</a></button>
Ребят, предлагаю оставить возможность для организатора тоже записаться на забег, так как в акаунте логика реализована так что это ничему не вредит в принципе. потому что на тоже же findarace можно и оганизовать и побежать в этом нет ничего страшного

2021-09-29 18:29 UTC, VoidPhantom commented on resources/views/layout/main.blade.php
> +            <a class="nav__item" href="{{ route('userSearch') }}">Чат</a>
Хотя раз на реализацию чата ушло нетривиальное количество усилий, то может быть лучше и оставить, чтобы можно было продемонстрировать. Даже если он не совсем вписывается в логически завершённую картину текущего продукта (который мы будем завтра показывать). Ну, в общем, на усмотрение остальных.

2021-09-29 18:32 UTC, julialunati commented on resources/views/layout/main.blade.php
> +            <a class="nav__item" href="{{ route('userSearch') }}">Чат</a>
я тоже оставляла, мне кажется ничего страшного, если будет одна ссылка с заглушкой, страшнее если оставим старый дизайн который по сравнению с новыми макетами совсем не фонтан :)

2021-09-29 18:38 UTC, VoidPhantom commented on resources/views/layout/main.blade.php
> +            <a class="nav__item" href="{{ route('userSearch') }}">Чат</a>
Что-то я не понял. Ты предлагаешь оставить неработающую ссылку на чат, но убрать страницы, связанные с чатом, потому что там примитивный дизайн? Или как?

2021-09-29 23:02 UTC, davidbraginsky commented on resources/views/races/show.blade.php
> +                </div>
Я сверстал как в макете) Ничего страшного в их наличии я не вижу. Можно просто не использовать их во время презентации и все.

2021-09-29 23:02 UTC, davidbraginsky commented on resources/views/races/show.blade.php
> +                <span class="race__time">9:00:00</span>
Исправил)

2021-09-29 23:03 UTC, davidbraginsky commented on resources/views/races/show.blade.php
> +                    <div class="race__infoContent">{{$race->start}}</div>
Это уже вопрос к дизайнеру)

2021-09-29 23:05 UTC, davidbraginsky commented on resources/views/layout/main.blade.php
> +            <a class="nav__item" href="{{ route('userSearch') }}">Чат</a>
Чат в сыром виде, но полностью работоспособен. Я считаю, что функциональность важнее дизайна и убирать его из навигации не вижу смысла.

2021-09-30 07:12 UTC, julialunati approved these changes

2021-09-30 09:14 UTC, VoidPhantom approved these changes
OK, делаю одобрение, хотя одно из запрошенных изменений всё-таки не сделано.

2021-09-30 10:58 UTC, merged