gallery
NikitaHasl/findrace pull request #36
Opened 2021-09-29 00:22 UTC by solaft

2021-09-29 13:16 UTC, VoidPhantom requested changes
Выглядит, конечно, здорово, но ведь это надо написать в виде Blade-представлений…

2021-09-29 15:41 UTC, julialunati commented
Я не думаю, что Катя успеет разобраться в blade до завтрашнего дня, поэтому хорошо бы если кто-то помог бы его вставить (при том что даже верстать ничего не надо)

2021-09-29 15:49 UTC, julialunati commented on gallery/index.html
> +                        <a href="http://projecthasl.h1n.ru/login" class="nav_auth_pohui">Главная</a>
интересное имя у класса

2021-09-30 13:37 UTC, VoidPhantom commented
Ну видимо эта вёрстка уже смёрджена в другом PR, так что я этот закрываю.

2021-09-30 13:37 UTC, closed without merging