Account view
NikitaHasl/findrace pull request #39
Opened 2021-09-29 14:57 UTC by julialunati

2021-09-29 15:14 UTC, VoidPhantom commented on resources/views/user/account.blade.php
> +                @endif
Это лучше выводить только участникам, а не организаторам

2021-09-29 15:19 UTC, VoidPhantom requested changes
Фантастика! 😲

Есть только несколько небольших комментариев:

2021-09-29 15:19 UTC, VoidPhantom commented on resources/views/user/account.blade.php
> +                @endif
Это лучше выводить только участникам, но не организаторам

2021-09-29 15:19 UTC, VoidPhantom commented on resources/views/user/account.blade.php
> +        @endif
Кажется, статистику мы решили убрать пока?

2021-09-29 15:19 UTC, VoidPhantom commented on resources/views/user/finishedRaces.blade.php
> +    Тут собраны все забеги, в которых ты принял участие и данные по ним.
```suggestion
    Тут собраны все забеги, в которых ты принял участие, и данные по ним.
```

2021-09-29 15:19 UTC, VoidPhantom commented on resources/views/user/changePassword.blade.php
> +                if (confirm("Вы уверены, что хотите удалить ваш аккаунт ?")) {
```suggestion
                if (confirm("Вы уверены, что хотите удалить ваш аккаунт?")) {
```

2021-09-29 15:20 UTC, julialunati commented on resources/views/user/account.blade.php
> +                @endif
я оставила функционал и для организаторов так как он также может бегать

2021-09-29 15:20 UTC, julialunati commented on resources/views/user/account.blade.php
> +        @endif
нет, так как нужен общий вид всех забегов

2021-09-29 15:22 UTC, VoidPhantom commented on resources/views/user/account.blade.php
> +        @endif
OK, логично

2021-09-29 15:23 UTC, julialunati commented on resources/views/user/finishedRaces.blade.php
> +    Тут собраны все забеги, в которых ты принял участие и данные по ним.
ну если мы будем обращать внимание на каждую запятую то завтра мы точно ничего не покажем)

2021-09-29 15:24 UTC, julialunati commented on resources/views/user/changePassword.blade.php
> +                if (confirm("Вы уверены, что хотите удалить ваш аккаунт ?")) {
этот пробел тут полжизни был а даже если нет то это не критично

2021-09-29 15:24 UTC, VoidPhantom commented on resources/views/user/account.blade.php
> +                @endif
Мне казалось, что мы решили, что участник и организатор — это разные роли с отдельной функциональностью. И если организатор хочет бегать, то он должен создать отдельный аккаунт участника. И кстати, если ты посмотришь на макеты, то там на этом месте у организаторов отображается количество созданных забегов и ссылка на них.

2021-09-29 15:26 UTC, julialunati commented on resources/views/user/account.blade.php
> +                @endif
ну а если получалось оставить то почему не оставить? и если посмотреть на макеты, то некоторых вообще нет, и многое приходилось брать из головы. я и так уже сутки потратила на эту фигню и переделывать не собираюсь так как эта проблема не стоит и выделенного яйца)

2021-09-29 15:27 UTC, julialunati commented on resources/views/user/finishedRaces.blade.php
> +    Тут собраны все забеги, в которых ты принял участие и данные по ним.
ок запятую уберу но другие фишки - сорян нет)

2021-09-29 15:27 UTC, VoidPhantom commented on resources/views/user/account.blade.php
> +                @endif
Ну хорошо

2021-09-29 15:30 UTC, VoidPhantom commented on resources/views/user/account.blade.php
> +            <div class="create-expl">Ты можещь создавать новые забеги</div>
```suggestion
            <div class="create-expl">Ты можешь создавать новые забеги</div>
```

2021-09-29 15:33 UTC, VoidPhantom approved these changes

2021-09-29 17:55 UTC, VoidPhantom commented
Кстати, я, получается, поторопился, когда брал на себя задание сделать выход через POST, потому что это, конечно же, задача для фронтендеров, и ты её, получается, выполнила ☺ Я тогда карточку в Джире на тебя перепишу и в code review закину.

2021-09-29 22:02 UTC, davidbraginsky approved these changes
Юля, молодец! 

Очень круто сделала)

2021-09-29 23:24 UTC, NikitaHasl approved these changes

2021-09-30 06:24 UTC, julialunati commented on resources/views/races/addResults.blade.php
> +    </form>
так как по макетам была нужна кнопка, а для inputa уже были стили и новые писать button не хотелось (потому что просто ссылку ввиде кнопки тоже сложновато оформить)

2021-09-30 06:56 UTC, merged