fix subscribe button
NikitaHasl/findrace pull request #40
Opened 2021-09-29 14:59 UTC by NikitaHasl

2021-09-29 15:04 UTC, VoidPhantom requested changes
Интерфейс для записи на забег не должен отображаться для организаторов. (Раньше так было, а здесь соответствующее условие было удалено.)

2021-09-29 16:08 UTC, NikitaHasl commented
> Интерфейс для записи на забег не должен отображаться для организаторов. (Раньше так было, а здесь соответствующее условие было удалено.)

Да, поспешил немного с условиями, сейчас исправлю.

2021-09-29 16:19 UTC, VoidPhantom approved these changes

2021-09-30 13:30 UTC, julialunati approved these changes

2021-09-30 14:05 UTC, merged